// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['webAPIKey']!,
    appId: '1:755405539897:web:f1302709e68377e3dedbe8',
    messagingSenderId: '755405539897',
    projectId: 'alinas-app',
    authDomain: 'alinas-app.firebaseapp.com',
    storageBucket: 'alinas-app.firebasestorage.app',
    measurementId: 'G-Z8L6RMGGDM',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['androidAPIKey']!,
    appId: '1:755405539897:android:8df40fed972a6934dedbe8',
    messagingSenderId: '755405539897',
    projectId: 'alinas-app',
    storageBucket: 'alinas-app.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['iosAPIKey']!,
    appId: '1:755405539897:ios:179d1e3920acf883dedbe8',
    messagingSenderId: '755405539897',
    projectId: 'alinas-app',
    storageBucket: 'alinas-app.firebasestorage.app',
    iosBundleId: 'com.example.journalApp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['macosAPIKey']!,
    appId: '1:755405539897:ios:179d1e3920acf883dedbe8',
    messagingSenderId: '755405539897',
    projectId: 'alinas-app',
    storageBucket: 'alinas-app.firebasestorage.app',
    iosBundleId: 'com.example.journalApp',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['windowsAPIKey']!,
    appId: '1:755405539897:web:578c16f7795c4069dedbe8',
    messagingSenderId: '755405539897',
    projectId: 'alinas-app',
    authDomain: 'alinas-app.firebaseapp.com',
    storageBucket: 'alinas-app.firebasestorage.app',
    measurementId: 'G-ZWZK56RD3J',
  );
}
